version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      -  discovery.type=single-node
    volumes:
      - $HOME/elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.6
    ports:
      - 5601:5601

  case-server:
#    image: powsybl/case-server:latest
    image: powsybl/case-server@sha256:a8e401025635c3107bf7ed9cea369e28caee713799a271a18e4fd78667081a6d
    ports:
      - 5000:80
    volumes:
      - $PWD/case-server-application.yml:/config/application.yml:Z
      - $HOME/cases:/cases:Z

  network-store-server:
#    image: powsybl/network-store-server:latest
    image: powsybl/network-store-server@sha256:434d1df27e160e6dbaac27b127bbcc72cf22b4c77bd54f1aa3b88bcc890ff682 
    ports:
      - 8080:80
    volumes:
      - $PWD/network-store-server-application.yml:/config/application.yml:Z
      - $PWD/cassandra.properties:/config/cassandra.properties:Z

  geo-data-server:
#    image: powsybl/geo-data-server:latest
    image: powsybl/geo-data-server@sha256:01a21e66f72b5153883dd94e3e24a661c9f2649cd62a24a6fd9030b46629ca73
    ports:
      - 8087:80
    volumes:
      - $PWD/geo-data-server-application.yml:/config/application.yml:Z
      - $PWD/cassandra.properties:/config/cassandra.properties:Z

  network-conversion-server:
#    image: powsybl/network-conversion-server:latest
    image: powsybl/network-conversion-server@sha256:7d2d6011bc7e3edebc5ca9ff8057532b0794ac4c69da8abede0980014d6b3a77 
    ports:
      - 5003:80
    volumes:
      - $PWD/network-conversion-server-application.yml:/config/application.yml:Z

  network-diff-server:
    image: network-diff-server:latest
    ports:
      - 6007:80
    volumes:
      - $PWD/network-diff-server-application.yml:/config/application.yml:Z

  network-diff-study-server:
    image: network-diff-study-server:latest
    ports:
      - 6008:80
    volumes:
      - $PWD/network-diff-study-server-application.yml:/config/application.yml:Z
      - $PWD/cassandra.properties:/config/cassandra.properties:Z

#  network-diff-study-app:
#    image: network-diff-study-app:latest
#    ports:
#      - 4200:80


