server:
  port: 80
  forward-headers-strategy: framework

network-store-server:
  preloading-strategy: COLLECTION
  base-uri: http://network-store-server/

network-geo-data:
  iterations: 5

cassandra-keyspace: geo_data

