server :
  port : 80

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB
  codec:
    max-in-memory-size: 100MB
  mvc:
    async:
      request-timeout: 180000

  rabbitmq:
    addresses: rabbitmq
    port: 5672

backing-services:
  case:
    base-uri: http://case-server/
  network-conversion:
    base-uri: http://network-conversion-server/
  network-diff:
    base-uri: http://network-diff-server/
  geo-server:
    base-uri: http://geo-data-server/


network-store-server:
  preloading-strategy: COLLECTION
  base-uri: http://network-store-server/ 


